<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjVLcAU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjVLcAU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUjVLcAU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUjVLcAU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUjVLcAU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UjVLcAU',
    'container.build_id' => 'e53ccfe9',
    'container.build_time' => 1737032815,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjVLcAU');
