<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_docs' => [[], ['_controller' => 'App\\Controller\\DocsController::index'], [], [['text', '/docs']], [], [], []],
    'app_get_donnees_virus' => [[], ['_controller' => 'App\\Controller\\DonneesVirusController::index'], [], [['text', '/donnees-virus']], [], [], []],
    'app_create_donnees_virus' => [[], ['_controller' => 'App\\Controller\\DonneesVirusController::create'], [], [['text', '/donnees-virus']], [], [], []],
    'app_delete_donnees_virus' => [['id'], ['_controller' => 'App\\Controller\\DonneesVirusController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/donnees-virus']], [], [], []],
    'app_get_pays' => [[], ['_controller' => 'App\\Controller\\PaysController::index'], [], [['text', '/pays']], [], [], []],
    'app_create_pays' => [[], ['_controller' => 'App\\Controller\\PaysController::create'], [], [['text', '/pays']], [], [], []],
    'app_delete_pays' => [['id'], ['_controller' => 'App\\Controller\\PaysController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pays']], [], [], []],
    'app_get_virus' => [[], ['_controller' => 'App\\Controller\\VirusController::index'], [], [['text', '/virus']], [], [], []],
    'app_create_virus' => [[], ['_controller' => 'App\\Controller\\VirusController::create'], [], [['text', '/virus']], [], [], []],
    'app_delete_virus' => [['id'], ['_controller' => 'App\\Controller\\VirusController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/virus']], [], [], []],
    'App\Controller\DocsController::index' => [[], ['_controller' => 'App\\Controller\\DocsController::index'], [], [['text', '/docs']], [], [], []],
    'App\Controller\DonneesVirusController::index' => [[], ['_controller' => 'App\\Controller\\DonneesVirusController::index'], [], [['text', '/donnees-virus']], [], [], []],
    'App\Controller\DonneesVirusController::create' => [[], ['_controller' => 'App\\Controller\\DonneesVirusController::create'], [], [['text', '/donnees-virus']], [], [], []],
    'App\Controller\DonneesVirusController::delete' => [['id'], ['_controller' => 'App\\Controller\\DonneesVirusController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/donnees-virus']], [], [], []],
    'App\Controller\PaysController::index' => [[], ['_controller' => 'App\\Controller\\PaysController::index'], [], [['text', '/pays']], [], [], []],
    'App\Controller\PaysController::create' => [[], ['_controller' => 'App\\Controller\\PaysController::create'], [], [['text', '/pays']], [], [], []],
    'App\Controller\PaysController::delete' => [['id'], ['_controller' => 'App\\Controller\\PaysController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pays']], [], [], []],
    'App\Controller\VirusController::index' => [[], ['_controller' => 'App\\Controller\\VirusController::index'], [], [['text', '/virus']], [], [], []],
    'App\Controller\VirusController::create' => [[], ['_controller' => 'App\\Controller\\VirusController::create'], [], [['text', '/virus']], [], [], []],
    'App\Controller\VirusController::delete' => [['id'], ['_controller' => 'App\\Controller\\VirusController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/virus']], [], [], []],
];
