<?php

namespace ContainerJeZmckY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LN1dKdJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LN1dKdJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LN1dKdJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DonneesVirusController::create' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\DonneesVirusController::delete' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\DonneesVirusController::index' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\PaysController::create' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\PaysController::delete' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\PaysController::index' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\VirusController::create' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'App\\Controller\\VirusController::delete' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'App\\Controller\\VirusController::index' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DonneesVirusController:create' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\DonneesVirusController:delete' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\DonneesVirusController:index' => ['privates', '.service_locator.7Nwt0MT', 'get_ServiceLocator_7Nwt0MTService', true],
            'App\\Controller\\PaysController:create' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\PaysController:delete' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\PaysController:index' => ['privates', '.service_locator.R8mYGRC', 'get_ServiceLocator_R8mYGRCService', true],
            'App\\Controller\\VirusController:create' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'App\\Controller\\VirusController:delete' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'App\\Controller\\VirusController:index' => ['privates', '.service_locator.Vvhr8LS', 'get_ServiceLocator_Vvhr8LSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DonneesVirusController::create' => '?',
            'App\\Controller\\DonneesVirusController::delete' => '?',
            'App\\Controller\\DonneesVirusController::index' => '?',
            'App\\Controller\\PaysController::create' => '?',
            'App\\Controller\\PaysController::delete' => '?',
            'App\\Controller\\PaysController::index' => '?',
            'App\\Controller\\VirusController::create' => '?',
            'App\\Controller\\VirusController::delete' => '?',
            'App\\Controller\\VirusController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DonneesVirusController:create' => '?',
            'App\\Controller\\DonneesVirusController:delete' => '?',
            'App\\Controller\\DonneesVirusController:index' => '?',
            'App\\Controller\\PaysController:create' => '?',
            'App\\Controller\\PaysController:delete' => '?',
            'App\\Controller\\PaysController:index' => '?',
            'App\\Controller\\VirusController:create' => '?',
            'App\\Controller\\VirusController:delete' => '?',
            'App\\Controller\\VirusController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
